"""
Professional PDF mission report generator.

Produces a multi-page A4 PDF via fpdf2 (pure Python, no system dependencies).
Charts are generated by render_pdf_charts.py (matplotlib → base64 PNG).
Uses the bundled Inter font for full Unicode support and a clean modern look.
"""

from __future__ import annotations

import base64
import io
import math
from pathlib import Path

import numpy as np
from fpdf import FPDF

from export.render_pdf_charts import (
    agl_heatmap_png,
    altitude_profile_png,
    route_overview_png,
    terrain_map_png,
)
from models import ManeuverType
from session import LastPlanData

# ── Fonts ─────────────────────────────────────────────────────────────────────

_FONTS_DIR = Path(__file__).parent / "fonts"


# ── Colors ────────────────────────────────────────────────────────────────────

_PRIMARY = (30, 144, 255)  # #1E90FF dodger blue (app primary)
_PRIMARY_DARK = (18, 90, 170)
_WHITE = (255, 255, 255)
_BG_PAGE = (255, 255, 255)
_BG_SURFACE = (245, 247, 250)  # card fills / zebra stripes
_TEXT = (13, 17, 23)  # #0d1117
_TEXT_MUTED = (110, 118, 129)  # #6e7681
_BORDER = (208, 215, 222)
_COVER_BG = (13, 17, 23)  # near-black hero zone

_SUCCESS = (0, 200, 83)
_WARNING = (255, 145, 0)
_DANGER = (255, 82, 82)
_SUCCESS_BG = (230, 255, 240)
_WARNING_BG = (255, 248, 230)
_DANGER_BG = (255, 235, 235)
_SUCCESS_TEXT = (27, 94, 32)
_WARNING_TEXT = (180, 72, 0)
_DANGER_TEXT = (183, 28, 28)


# ── Layout ────────────────────────────────────────────────────────────────────

_MARGIN = 20  # mm
_PAGE_W = 210  # A4
_PAGE_H = 297
_CONTENT_W = _PAGE_W - 2 * _MARGIN  # 170 mm
_ROW_H = 6.5
_CARD_R = 1.5  # corner radius
_NB_ALIAS = "{nb}"  # total pages alias


# ── Helpers ───────────────────────────────────────────────────────────────────


def _fmt_dist(m: float) -> str:
    return f"{m / 1000:.2f} km" if m >= 1000 else f"{m:.0f} m"


def _fmt_time(s: float) -> str:
    m, sec = divmod(int(s), 60)
    h, m = divmod(m, 60)
    return f"{h}h {m:02d}m {sec:02d}s" if h else f"{m}m {sec:02d}s"


def _fmt_area(m2: float | None) -> str:
    if m2 is None:
        return "-"
    return f"{m2:.0f} m\u00b2"


def _b64_image(b64: str) -> io.BytesIO:
    return io.BytesIO(base64.b64decode(b64))


def _status(data: LastPlanData) -> tuple[tuple, tuple, tuple, str]:
    """Return (bg, border, text_color, label) based on violations."""
    violations = data.meta.violations or []
    hard = [v for v in violations if v.kind != "surface_warning"]
    if hard:
        return _DANGER_BG, _DANGER, _DANGER_TEXT, "VIOLATIONS DETECTED — REVIEW REQUIRED"
    if violations or data.meta.warning:
        return _WARNING_BG, _WARNING, _WARNING_TEXT, "WARNINGS PRESENT — REVIEW BEFORE FLIGHT"
    return _SUCCESS_BG, _SUCCESS, _SUCCESS_TEXT, "ALL CLEAR — NO SAFETY VIOLATIONS"


def _clearance_color(m: float | None) -> tuple:
    if m is None:
        return _TEXT_MUTED
    return _SUCCESS if m > 15 else _WARNING if m > 5 else _DANGER


_KIND_LABEL: dict[str, str] = {
    "terrain_band": "Terrain band too narrow",
    "slope": "Slope limit exceeded",
    "vertical": "Below surface model",
    "horizontal": "Safety bubble obstacle",
    "surface_warning": "Above max AGL",
    "camera_range": "Camera range exceeded",
}


# ── PDF class ─────────────────────────────────────────────────────────────────


class MissionPDF(FPDF):
    """FPDF subclass with FlyHigh-specific drawing helpers."""

    def __init__(self) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")

        # Load Inter font (full Unicode support)
        regular = _FONTS_DIR / "Inter-Regular.ttf"
        bold = _FONTS_DIR / "Inter-Bold.ttf"
        if regular.exists() and bold.exists():
            self.add_font("Inter", fname=str(regular))
            self.add_font("Inter", "B", fname=str(bold))
            self._font_family = "Inter"
        else:
            # Graceful fallback if fonts not installed
            self._font_family = "Helvetica"

        self.set_margins(_MARGIN, _MARGIN, _MARGIN)
        self.set_auto_page_break(auto=True, margin=22)
        self.alias_nb_pages(_NB_ALIAS)
        self.mission_name = ""

    def _f(self, style: str = "", size: float = 9) -> None:
        """Shorthand to set font."""
        self.set_font(self._font_family, style, size)

    # ── Page chrome ───────────────────────────────────────────────────────────

    def footer(self) -> None:
        self.set_y(-14)
        self.set_draw_color(*_BORDER)
        self.set_line_width(0.3)
        self.line(_MARGIN, self.get_y(), _MARGIN + _CONTENT_W, self.get_y())
        self.ln(2)
        self._f("", 7)
        self.set_text_color(*_TEXT_MUTED)
        label = (
            f"{self.mission_name}  \u00b7  FlyHigh  \u00b7  Page {self.page_no()} of {_NB_ALIAS}"
        )
        self.cell(0, 5, label, align="C")

    def header_bar(self, subtitle: str) -> None:
        """Minimal accent header: left pillar + label + bottom rule."""
        y = self.get_y()

        # Left primary pillar
        self.set_fill_color(*_PRIMARY)
        self.rect(_MARGIN, y, 2.5, 9, style="F")

        # Label
        self.set_xy(_MARGIN + 5, y + 1)
        self._f("B", 8)
        self.set_text_color(*_TEXT_MUTED)
        self.cell(0, 7, subtitle, ln=0)

        # Bottom rule
        rule_y = y + 10
        self.set_draw_color(*_BORDER)
        self.set_line_width(0.3)
        self.line(_MARGIN, rule_y, _MARGIN + _CONTENT_W, rule_y)

        self.set_y(rule_y + 5)
        self.set_text_color(*_TEXT)

    def section_title(self, text: str) -> None:
        """Bold section heading with a light rule beneath."""
        self.ln(5)
        self._f("B", 8.5)
        self.set_text_color(*_TEXT)
        self.cell(_CONTENT_W, 5, text, ln=1)
        y = self.get_y()
        self.set_draw_color(*_BORDER)
        self.set_line_width(0.3)
        self.line(_MARGIN, y, _MARGIN + _CONTENT_W, y)
        self.ln(4)
        self.set_text_color(*_TEXT)
        self.set_draw_color(0, 0, 0)
        self.set_line_width(0.2)

    def status_stamp(self, data: LastPlanData) -> None:
        """Tinted rounded-feel block for mission safety status."""
        bg, border_col, text_col, label = _status(data)
        y = self.get_y()

        self.set_fill_color(*bg)
        self.set_draw_color(*border_col)
        self.set_line_width(0.4)
        self.rect(_MARGIN, y, _CONTENT_W, 18, style="FD")

        # Left accent
        self.set_fill_color(*border_col)
        self.rect(_MARGIN, y, 3, 18, style="F")

        self._f("B", 9)
        self.set_text_color(*text_col)
        self.set_xy(_MARGIN + 3, y + 5)
        self.cell(_CONTENT_W - 3, 8, label, align="C", ln=1)

        self.ln(4)
        self.set_text_color(*_TEXT)

    # ── Content blocks ────────────────────────────────────────────────────────

    def kpi_grid(self, kpis: list[tuple[str, str, tuple]], cols: int = 3) -> None:
        """Row(s) of tall KPI cards with colored top accent bar."""
        gap = 3.0
        card_w = (_CONTENT_W - gap * (cols - 1)) / cols
        card_h = 26.0
        y0 = self.get_y()

        for i, (label, value, color) in enumerate(kpis):
            col = i % cols
            row = i // cols
            x = _MARGIN + col * (card_w + gap)
            y = y0 + row * (card_h + gap)

            # Card background
            self.set_fill_color(*_BG_SURFACE)
            self.set_draw_color(*_BORDER)
            self.set_line_width(0.2)
            self.rect(x, y, card_w, card_h, style="FD")

            # Color accent bar on top (2 mm)
            self.set_fill_color(*color)
            self.rect(x, y, card_w, 2, style="F")

            # Value
            self.set_xy(x + 2, y + 4)
            self._f("B", 14)
            self.set_text_color(*color)
            self.cell(card_w - 4, 9, value, align="C", ln=0)

            # Label
            self.set_xy(x + 2, y + 15)
            self._f("", 7)
            self.set_text_color(*_TEXT_MUTED)
            self.cell(card_w - 4, 5, label.upper(), align="C", ln=0)

        rows_used = math.ceil(len(kpis) / cols)
        self.set_y(y0 + rows_used * (card_h + gap) + 2)
        self.set_text_color(*_TEXT)

    def data_table(self, rows: list[tuple[str, str]], label_frac: float = 0.45) -> None:
        """Zebra-striped two-column label/value table."""
        label_w = _CONTENT_W * label_frac
        value_w = _CONTENT_W - label_w

        for i, (lbl, val) in enumerate(rows):
            y = self.get_y()
            if i % 2 == 1:
                self.set_fill_color(*_BG_SURFACE)
                self.rect(_MARGIN, y, _CONTENT_W, _ROW_H, style="F")

            self.set_xy(_MARGIN + 4, y)
            self._f("", 8)
            self.set_text_color(*_TEXT_MUTED)
            self.cell(label_w - 4, _ROW_H, lbl, ln=0)

            self._f("B", 8)
            self.set_text_color(*_TEXT)
            self.cell(value_w, _ROW_H, val, ln=1)

        self.ln(2)
        self.set_text_color(*_TEXT)

    def violation_table(self, violations: list) -> None:
        """Color-coded table of violations, with manual page-break protection."""
        col_w = [8, 48, 82, 32]
        headers = ["#", "Type", "Description", "Location"]

        def _header() -> None:
            self.set_fill_color(*_PRIMARY)
            hy = self.get_y()
            self.rect(_MARGIN, hy, _CONTENT_W, _ROW_H, style="F")
            self._f("B", 6.5)
            self.set_text_color(*_WHITE)
            hx = _MARGIN
            for hdr, hw in zip(headers, col_w):
                self.set_xy(hx + 1, hy)
                self.cell(hw - 1, _ROW_H, hdr.upper(), ln=0)
                hx += hw
            self.set_y(hy + _ROW_H)

        _header()

        for i, v in enumerate(violations):
            # Manual page break — prevent rect/cell split across pages
            if self.get_y() + _ROW_H > _PAGE_H - 25:
                self.add_page()
                _header()

            y = self.get_y()
            is_safety = getattr(v, "category", "safety") == "safety"
            bg = _DANGER_BG if is_safety else _WARNING_BG
            tcol = _DANGER_TEXT if is_safety else _WARNING_TEXT

            self.set_fill_color(*bg)
            self.rect(_MARGIN, y, _CONTENT_W, _ROW_H, style="F")

            # Truncate description to fit the column
            self._f("", 7)
            desc = v.description or ""
            max_w = col_w[2] - 3
            while desc and self.get_string_width(desc) > max_w:
                desc = desc[:-1]
            if desc != v.description:
                desc = desc.rstrip()[:-1] + "\u2026"

            loc = f"{v.lat:.5f}, {v.lon:.5f}" if (v.lat is not None and v.lon is not None) else "-"
            cells = [str(i + 1), _KIND_LABEL.get(v.kind, v.kind), desc, loc]
            self.set_text_color(*tcol)
            self._f("B" if is_safety else "", 7)
            x = _MARGIN
            for text, cw in zip(cells, col_w):
                self.set_xy(x + 1, y)
                self.cell(cw - 1, _ROW_H, text, ln=0)
                x += cw
            self.set_y(y + _ROW_H)

        self.ln(2)
        self.set_text_color(*_TEXT)

    def stat_chips(self, chips: list[tuple[str, str]]) -> None:
        """Small bordered chips for secondary stats."""
        x = float(_MARGIN)
        y = self.get_y()
        ch_h = 7.0
        gap = 2.5

        for label, value in chips:
            text = f"{value}  {label}"
            self._f("", 7.5)
            w = self.get_string_width(text) + 8

            if x + w > _MARGIN + _CONTENT_W:
                x = float(_MARGIN)
                y += ch_h + gap

            self.set_fill_color(*_BG_SURFACE)
            self.set_draw_color(*_BORDER)
            self.set_line_width(0.2)
            self.rect(x, y, w, ch_h, style="FD")

            val_w = self.get_string_width(value) + 1
            self.set_xy(x + 4, y + 1)
            self._f("B", 7.5)
            self.set_text_color(*_TEXT)
            self.cell(val_w, ch_h - 2, value, ln=0)

            self._f("", 7.5)
            self.set_text_color(*_TEXT_MUTED)
            self.cell(w - val_w - 5, ch_h - 2, label, ln=0)

            x += w + gap

        self.set_y(y + ch_h + 4)
        self.set_text_color(*_TEXT)

    def integrity_block(self, lines: list[str]) -> None:
        """Monospaced green-tinted block for route integrity info."""
        row_h = _ROW_H
        block_h = len(lines) * row_h + 8
        y0 = self.get_y()

        self.set_fill_color(230, 245, 233)
        self.set_draw_color(165, 214, 167)
        self.set_line_width(0.2)
        self.rect(_MARGIN, y0, _CONTENT_W, block_h, style="FD")

        self.set_font("Courier", "", 7.5)
        self.set_text_color(46, 125, 50)
        for i, line in enumerate(lines):
            self.set_xy(_MARGIN + 5, y0 + 4 + i * row_h)
            self.cell(_CONTENT_W - 10, row_h, line, ln=0)

        self.set_y(y0 + block_h + 4)
        self.set_text_color(*_TEXT)
        self.set_draw_color(0, 0, 0)
        self.set_line_width(0.2)

    def embed_image(self, b64: str, caption: str = "", h: float = 0) -> None:
        """Embed a base64 PNG full-width with an optional caption."""
        kwargs: dict = dict(x=_MARGIN, w=_CONTENT_W)
        if h:
            kwargs["h"] = h
        self.image(_b64_image(b64), **kwargs)
        self.ln(1)
        if caption:
            self._f("", 7)
            self.set_text_color(*_TEXT_MUTED)
            self.cell(_CONTENT_W, 4, caption, align="C", ln=1)
            self.set_text_color(*_TEXT)
        self.ln(2)

    def two_col_images(
        self,
        left_b64: str,
        right_b64: str | None,
        left_cap: str = "",
        right_cap: str = "",
        height: float = 90,
    ) -> None:
        """Two images side by side with captions."""
        col_w = (_CONTENT_W - 4) / 2
        y = self.get_y()

        self.image(_b64_image(left_b64), x=_MARGIN, y=y, w=col_w, h=height)
        if right_b64:
            self.image(_b64_image(right_b64), x=_MARGIN + col_w + 4, y=y, w=col_w, h=height)

        cap_y = y + height + 1
        self._f("", 7)
        self.set_text_color(*_TEXT_MUTED)
        if left_cap:
            self.set_xy(_MARGIN, cap_y)
            self.cell(col_w, 4, left_cap, align="C", ln=0)
        if right_cap and right_b64:
            self.set_xy(_MARGIN + col_w + 4, cap_y)
            self.cell(col_w, 4, right_cap, align="C", ln=0)

        self.set_y(cap_y + 5)
        self.set_text_color(*_TEXT)


# ── Page body builders ────────────────────────────────────────────────────────
# Each builder receives a pdf with a page already added by the caller.


def _cover_page_body(pdf: MissionPDF, data: LastPlanData, operator: str, organization: str) -> None:
    """Hero-style cover: dark zone (top 100 mm) + white meta zone."""
    # Dark hero zone
    pdf.set_fill_color(*_COVER_BG)
    pdf.rect(0, 0, _PAGE_W, 100, style="F")

    # "FlyHigh" wordmark
    pdf.set_xy(0, 27)
    pdf.set_font(pdf._font_family, "B", 32)
    pdf.set_text_color(*_PRIMARY)
    pdf.cell(_PAGE_W, 12, "FlyHigh", align="C", ln=1)

    # Tagline
    pdf.set_x(0)
    pdf.set_font(pdf._font_family, "", 11)
    pdf.set_text_color(180, 190, 200)
    pdf.cell(_PAGE_W, 6, "Autonomous Drone Mission Planner", align="C", ln=1)

    # Accent rule
    rule_x = (_PAGE_W - 60) / 2
    pdf.set_draw_color(*_PRIMARY)
    pdf.set_line_width(0.6)
    pdf.line(rule_x, pdf.get_y() + 3, rule_x + 60, pdf.get_y() + 3)
    pdf.ln(10)

    # Mission name
    mission = data.mission_name or "Untitled Mission"
    pdf.set_x(0)
    pdf.set_font(pdf._font_family, "B", 22)
    pdf.set_text_color(*_WHITE)
    pdf.cell(_PAGE_W, 10, mission[:40], align="C", ln=1)

    # Route ID
    pdf.ln(4)
    pdf.set_x(0)
    pdf.set_font(pdf._font_family, "", 8)
    pdf.set_text_color(100, 115, 130)
    pdf.cell(_PAGE_W, 5, f"Route ID: {data.route_hash[:28]}...", align="C", ln=1)

    # ── White meta zone ───────────────────────────────────────────────────────
    y_meta = 110

    # 3-column meta row
    col_w = _CONTENT_W / 3
    gen_dt = data.generated_at.replace("T", " ")[:16] + " UTC"
    op_val = operator or "\u2014"
    org_val = organization or "\u2014"
    metas = [("DATE", gen_dt), ("OPERATOR", op_val), ("ORGANIZATION", org_val)]

    for i, (lbl, val) in enumerate(metas):
        x = _MARGIN + i * col_w
        # Vertical divider (except first)
        if i > 0:
            pdf.set_draw_color(*_BORDER)
            pdf.set_line_width(0.2)
            pdf.line(x, y_meta, x, y_meta + 18)

        pdf.set_xy(x, y_meta + 2)
        pdf.set_font(pdf._font_family, "", 7)
        pdf.set_text_color(*_TEXT_MUTED)
        pdf.cell(col_w, 5, lbl, align="C", ln=0)

        pdf.set_xy(x, y_meta + 8)
        pdf.set_font(pdf._font_family, "B", 9)
        pdf.set_text_color(*_TEXT)
        pdf.cell(col_w, 6, val[:28], align="C", ln=0)

    # Thin separator
    sep_y = y_meta + 22
    pdf.set_draw_color(*_BORDER)
    pdf.set_line_width(0.3)
    pdf.line(_MARGIN, sep_y, _MARGIN + _CONTENT_W, sep_y)

    pdf.set_y(sep_y + 8)
    pdf.status_stamp(data)

    # Confidentiality notice at bottom
    pdf.set_xy(_MARGIN, _PAGE_H - 25)
    pdf.set_font(pdf._font_family, "", 7)
    pdf.set_text_color(*_TEXT_MUTED)
    pdf.cell(_CONTENT_W, 5, "CONFIDENTIAL \u2014 FOR AUTHORIZED PERSONNEL ONLY", align="C", ln=1)


def _toc_page(pdf: MissionPDF, toc_map: dict[str, int]) -> None:
    """Table of contents with dot-leader rows."""
    pdf.add_page()
    pdf.header_bar("TABLE OF CONTENTS")

    pdf.set_y(pdf.get_y() + 4)
    pdf.set_font(pdf._font_family, "B", 18)
    pdf.set_text_color(*_TEXT)
    pdf.cell(_CONTENT_W, 10, "Contents", ln=1)
    pdf.ln(4)

    for i, (name, page_num) in enumerate(toc_map.items()):
        y_row = pdf.get_y()
        row_h = 12.0

        # Alternate background
        if i % 2 == 0:
            pdf.set_fill_color(*_BG_SURFACE)
            pdf.rect(_MARGIN, y_row, _CONTENT_W, row_h, style="F")

        # Number badge
        badge_w, badge_h = 8, 7
        pdf.set_fill_color(*_PRIMARY)
        pdf.rect(_MARGIN + 1, y_row + 2.5, badge_w, badge_h, style="F")
        pdf.set_font(pdf._font_family, "B", 7)
        pdf.set_text_color(*_WHITE)
        pdf.set_xy(_MARGIN + 1, y_row + 2.5)
        pdf.cell(badge_w, badge_h, str(i + 1), align="C", ln=0)

        # Section name
        pdf.set_font(pdf._font_family, "B", 10)
        pdf.set_text_color(*_TEXT)
        pdf.set_xy(_MARGIN + 12, y_row + 3)
        pdf.cell(100, 6, name, ln=0)

        # Page number (right-aligned)
        pdf.set_font(pdf._font_family, "B", 10)
        pdf.set_text_color(*_PRIMARY)
        pdf.set_xy(_MARGIN + _CONTENT_W - 18, y_row + 3)
        pdf.cell(18, 6, str(page_num), align="R", ln=0)

        # Dot leader
        name_end_x = _MARGIN + 12 + pdf.get_string_width(name) + 2
        page_start_x = _MARGIN + _CONTENT_W - 22
        if page_start_x > name_end_x + 6:
            mid_y = y_row + 6.5
            pdf.set_draw_color(*_BORDER)
            pdf.set_line_width(0.2)
            pdf.set_dash_pattern(dash=0.8, gap=1.8)
            pdf.line(name_end_x + 2, mid_y, page_start_x - 2, mid_y)
            pdf.set_dash_pattern()  # reset

        pdf.set_y(y_row + row_h)

    pdf.set_text_color(*_TEXT)


def _route_page_body(pdf: MissionPDF, data: LastPlanData, route_img: str) -> None:
    """Full-page route overview map."""
    pdf.header_bar("ROUTE OVERVIEW")
    pdf.section_title("Mission Route Map")
    pdf.embed_image(
        route_img,
        caption="Route coloured by AGL clearance (green = safe, amber = tight, red = critical)",
        h=155,
    )


def _summary_page_body(pdf: MissionPDF, data: LastPlanData) -> None:
    """KPIs, stat chips, violations."""
    pdf.header_bar("MISSION SUMMARY")
    m = data.meta

    pdf.section_title("Key Performance Indicators")
    pdf.kpi_grid(
        [
            ("Total distance", _fmt_dist(m.total_distance_m), _PRIMARY),
            ("Flight time", _fmt_time(m.flight_time_s), (0, 168, 150)),
            (
                "Min clearance",
                f"{m.min_clearance_m:.0f} m" if m.min_clearance_m is not None else "\u2014",
                _clearance_color(m.min_clearance_m),
            ),
            (
                "Mean clearance",
                f"{m.mean_clearance_m:.0f} m" if m.mean_clearance_m is not None else "\u2014",
                (85, 139, 47),
            ),
            ("Coverage area", _fmt_area(m.covered_area_m2), (120, 80, 200)),
        ]
    )

    terrain_res = f"{m.terrain_resolution_m:.1f} m/px" if m.terrain_resolution_m else "\u2014"
    pdf.stat_chips(
        [
            ("Waypoints", str(len(data.waypoint_indices))),
            ("POIs", str(len(data.poi_indices))),
            ("Terrain res.", terrain_res),
            ("Violations", str(len(m.violations or []))),
            ("Tight segs", str(m.tight_segment_count or 0)),
        ]
    )

    if m.violations:
        safety_v = [v for v in m.violations if getattr(v, "category", "safety") == "safety"]
        product_poi_v = [v for v in m.violations if getattr(v, "category", "") == "product_poi"]
        product_rte_v = [v for v in m.violations if getattr(v, "category", "") == "product_route"]

        if safety_v:
            pdf.section_title(f"Safety Violations ({len(safety_v)})")
            pdf.violation_table(safety_v)
        if product_poi_v:
            pdf.section_title(f"Scan Area Quality Issues ({len(product_poi_v)})")
            pdf.violation_table(product_poi_v)
        if product_rte_v:
            pdf.section_title(f"Transit Route Quality Issues ({len(product_rte_v)})")
            pdf.violation_table(product_rte_v)


def _safety_page_body(
    pdf: MissionPDF, data: LastPlanData, agl_img: str, terrain_img: str | None
) -> None:
    """AGL heatmap and terrain map side by side."""
    pdf.header_bar("SAFETY ANALYSIS")
    pdf.section_title("AGL Clearance & Terrain")

    pdf._f("", 8)
    pdf.set_text_color(*_TEXT_MUTED)
    pdf.cell(
        _CONTENT_W,
        5,
        "Thresholds:  Green (>15 m) comfortable   Amber (5\u201315 m) tight   Red (<5 m) critical",
        ln=1,
    )
    pdf.ln(3)
    pdf.set_text_color(*_TEXT)

    if terrain_img:
        pdf.two_col_images(
            agl_img,
            terrain_img,
            left_cap="AGL clearance heat map",
            right_cap="Terrain elevation beneath route (m MSL)",
            height=90,
        )
    else:
        pdf.embed_image(agl_img, caption="AGL clearance heat map", h=90)
        pdf._f("", 7.5)
        pdf.set_text_color(*_TEXT_MUTED)
        pdf.cell(_CONTENT_W, 6, "Terrain map unavailable (no raster data)", align="C", ln=1)
        pdf.set_text_color(*_TEXT)


def _profile_page_body(pdf: MissionPDF, data: LastPlanData, profile_img: str) -> None:
    """Altitude profile chart + statistics."""
    pdf.header_bar("ALTITUDE PROFILE")
    pdf.section_title("Route Altitude Profile")
    pdf.embed_image(
        profile_img,
        caption="Blue = drone altitude (MSL)  \u00b7  Brown = terrain  \u00b7  Green band = allowed AGL range",
        h=105,
    )

    valid_agl = data.agl_arr[np.isfinite(data.agl_arr)]
    alts = data.final_alts
    pdf.section_title("Altitude Statistics")
    pdf.data_table(
        [
            ("Max altitude (MSL)", f"{alts.max():.1f} m"),
            ("Min altitude (MSL)", f"{alts.min():.1f} m"),
            ("Mean altitude (MSL)", f"{alts.mean():.1f} m"),
            ("Max AGL clearance", f"{valid_agl.max():.1f} m" if valid_agl.size else "\u2014"),
            ("Min AGL clearance", f"{valid_agl.min():.1f} m" if valid_agl.size else "\u2014"),
            ("Mean AGL clearance", f"{valid_agl.mean():.1f} m" if valid_agl.size else "\u2014"),
        ]
    )


def _poi_page_body(pdf: MissionPDF, data: LastPlanData) -> None:
    """POI detail cards (one per POI, auto-paginate)."""
    if not data.pois:
        return

    pdf.header_bar("POINT-OF-INTEREST DETAILS")
    pdf.section_title("POI Maneuver Plans")

    for j, poi in enumerate(data.pois):
        m = poi.maneuver
        name = poi.name or f"POI {j + 1}"
        agl_min = m.poi_min_agl_m if m.poi_min_agl_m is not None else data.fc.min_agl_m
        agl_max = m.poi_max_agl_m if m.poi_max_agl_m is not None else data.fc.max_agl_m
        poi_dist = data.poi_distances[j] if j < len(data.poi_distances) else None
        maneuver_label = {
            ManeuverType.LAWNMOWER: "Lawnmower",
            ManeuverType.WARP_WEFT: "Warp & Weft",
            ManeuverType.SMART_LAWNMOWER: "Smart Lawnmower",
        }.get(m.type, m.type)
        poly_note = " (custom polygon)" if m.polygon else ""

        rows = [
            ("Coordinates", f"{poi.point.lat:.6f}, {poi.point.lon:.6f}"),
            ("Maneuver type", f"{maneuver_label}{poly_note}"),
            (
                "Coverage area",
                f"{m.width_m:.0f} m \u00d7 {m.height_m:.0f} m = {_fmt_area(m.width_m * m.height_m)}",
            ),
            ("Sweep spacing", f"{m.sweep_spacing_m:.1f} m"),
            ("AGL band", f"{agl_min:.0f} \u2013 {agl_max:.0f} m"),
            ("Distance on route", _fmt_dist(poi_dist) if poi_dist is not None else "\u2014"),
        ]
        card_h = len(rows) * _ROW_H + 22
        y0 = pdf.get_y()
        if y0 + card_h > _PAGE_H - 28:
            pdf.add_page()
            pdf.header_bar("POINT-OF-INTEREST DETAILS (cont.)")
            y0 = pdf.get_y()

        # Card outline
        pdf.set_fill_color(*_BG_SURFACE)
        pdf.set_draw_color(*_BORDER)
        pdf.set_line_width(0.2)
        pdf.rect(_MARGIN, y0, _CONTENT_W, card_h, style="FD")

        # Left accent (primary blue)
        pdf.set_fill_color(*_PRIMARY)
        pdf.rect(_MARGIN, y0, 3, card_h, style="F")

        # Number badge
        bx, by = _MARGIN + 6, y0 + 5
        pdf.set_fill_color(*_PRIMARY)
        pdf.ellipse(bx, by, 7, 7, style="F")
        pdf.set_font(pdf._font_family, "B", 9)
        pdf.set_text_color(*_WHITE)
        pdf.set_xy(bx, by + 0.5)
        pdf.cell(7, 6, str(j + 1), align="C", ln=0)

        # POI name
        pdf.set_font(pdf._font_family, "B", 11)
        pdf.set_text_color(*_TEXT)
        pdf.set_xy(_MARGIN + 17, y0 + 6)
        pdf.cell(90, 6, name, ln=0)

        # Maneuver chip
        chip_text = maneuver_label.upper()
        pdf.set_font(pdf._font_family, "B", 6)
        chip_w = pdf.get_string_width(chip_text) + 8
        chip_x = _MARGIN + _CONTENT_W - chip_w - 5
        pdf.set_fill_color(225, 240, 255)
        pdf.set_draw_color(*_PRIMARY)
        pdf.set_line_width(0.15)
        pdf.rect(chip_x, y0 + 6, chip_w, 6, style="FD")
        pdf.set_text_color(*_PRIMARY)
        pdf.set_xy(chip_x + 3, y0 + 7)
        pdf.cell(chip_w - 6, 4, chip_text, ln=0)

        # Separator under header
        sep_y = y0 + 15
        pdf.set_draw_color(*_BORDER)
        pdf.set_line_width(0.2)
        pdf.line(_MARGIN + 3, sep_y, _MARGIN + _CONTENT_W, sep_y)

        # Detail rows
        label_w = _CONTENT_W * 0.4
        for i, (lbl, val) in enumerate(rows):
            ry = y0 + 17 + i * _ROW_H
            if i % 2 == 1:
                pdf.set_fill_color(238, 241, 245)
                pdf.rect(_MARGIN + 3, ry, _CONTENT_W - 3, _ROW_H, style="F")
            pdf.set_xy(_MARGIN + 6, ry)
            pdf.set_font(pdf._font_family, "", 7.5)
            pdf.set_text_color(*_TEXT_MUTED)
            pdf.cell(label_w, _ROW_H, lbl, ln=0)
            pdf.set_font(pdf._font_family, "B", 7.5)
            pdf.set_text_color(*_TEXT)
            pdf.cell(_CONTENT_W - label_w - 7, _ROW_H, val, ln=0)

        pdf.set_y(y0 + card_h + 6)

    pdf.set_text_color(*_TEXT)


def _config_page_body(
    pdf: MissionPDF, data: LastPlanData, operator: str, organization: str
) -> None:
    """Flight parameters, integrity hash, status."""
    pdf.header_bar("CONFIGURATION & INTEGRITY")
    fc = data.fc

    cfg_fields = [
        ("Min AGL", f"{fc.min_agl_m} m"),
        ("Max AGL", f"{fc.max_agl_m} m"),
        ("Safety radius", f"{fc.point_radius_m} m"),
        ("Camera range radius", f"{fc.max_surface_radius_m} m"),
        ("Cruise speed", f"{fc.cruise_speed_ms} m/s"),
        ("Climb rate", f"{fc.climb_rate_ms} m/s"),
        ("Route spacing", f"{fc.spacing_m} m"),
        ("Optimize POI order", "Yes" if fc.optimize_poi_order else "No"),
        ("Smart Route", "Yes" if fc.smart_route else "No"),
        ("Min altitude step", f"{fc.min_altitude_step_m} m"),
    ]
    if fc.max_slope_ratio is not None:
        cfg_fields.append(("Max slope ratio", f"1:{1 / fc.max_slope_ratio:.0f}"))
    if fc.smart_route:
        cfg_fields.append(("Smart Route corridor", f"{fc.smart_route_corridor_m} m"))

    pdf.section_title("Flight Parameters")
    _draw_two_col_table(pdf, cfg_fields)

    gen_utc = data.generated_at.replace("T", " ") + " UTC"
    op_str = (operator or "\u2014") + (f" / {organization}" if organization else "")
    pdf.section_title("Route Integrity")
    pdf.integrity_block(
        [
            f"SHA-256 Route ID: {data.route_hash}",
            f"Generated:        {gen_utc}",
            f"Mission:          {data.mission_name or 'Untitled'}",
            f"Operator:         {op_str}",
        ]
    )

    pdf.section_title("Mission Status")
    pdf.status_stamp(data)


def _draw_two_col_table(pdf: MissionPDF, rows: list[tuple[str, str]]) -> None:
    """Render key/value rows in two side-by-side columns."""
    half = math.ceil(len(rows) / 2)
    left = rows[:half]
    right = rows[half:]
    col_w = (_CONTENT_W - 4) / 2
    label_w = col_w * 0.55

    def draw_col(items: list[tuple[str, str]], x_off: float) -> float:
        for i, (lbl, val) in enumerate(items):
            y = pdf.get_y()
            if i % 2 == 1:
                pdf.set_fill_color(*_BG_SURFACE)
                pdf.rect(_MARGIN + x_off, y, col_w, _ROW_H, style="F")
            pdf.set_xy(_MARGIN + x_off + 4, y)
            pdf.set_font(pdf._font_family, "", 8)
            pdf.set_text_color(*_TEXT_MUTED)
            pdf.cell(label_w, _ROW_H, lbl, ln=0)
            pdf.set_font(pdf._font_family, "B", 8)
            pdf.set_text_color(*_TEXT)
            pdf.cell(col_w - label_w - 4, _ROW_H, val, ln=1)
        return pdf.get_y()

    y_start = pdf.get_y()
    y_left_end = draw_col(left, 0)
    pdf.set_y(y_start)
    y_right_end = draw_col(right, col_w + 4)
    pdf.set_y(max(y_left_end, y_right_end) + 2)
    pdf.set_text_color(*_TEXT)


# ── Two-pass generator ────────────────────────────────────────────────────────


def _build_pdf(
    data: LastPlanData,
    operator: str,
    organization: str,
    route_img: str,
    agl_img: str,
    profile_img: str,
    terrain_img: str | None,
    include_toc: bool,
    toc_map: dict[str, int] | None,
) -> tuple[MissionPDF, dict[str, int]]:
    """Build full PDF. Returns (pdf, page_map).

    page_map records the page each named section starts on (only populated
    when include_toc=False).
    """
    pdf = MissionPDF()
    pdf.mission_name = data.mission_name or "FlyHigh Mission"
    page_map: dict[str, int] = {}

    # Cover (page 1)
    pdf.add_page()
    _cover_page_body(pdf, data, operator, organization)

    # TOC (page 2) — only on second pass
    if include_toc and toc_map:
        _toc_page(pdf, toc_map)

    # Route overview
    pdf.add_page()
    page_map["Route Overview"] = pdf.page_no()
    _route_page_body(pdf, data, route_img)

    # Mission summary
    pdf.add_page()
    page_map["Mission Summary"] = pdf.page_no()
    _summary_page_body(pdf, data)

    # Safety analysis
    pdf.add_page()
    page_map["Safety Analysis"] = pdf.page_no()
    _safety_page_body(pdf, data, agl_img, terrain_img)

    # Altitude profile
    pdf.add_page()
    page_map["Altitude Profile"] = pdf.page_no()
    _profile_page_body(pdf, data, profile_img)

    # POI details (only if there are POIs)
    if data.pois:
        pdf.add_page()
        page_map["POI Details"] = pdf.page_no()
        _poi_page_body(pdf, data)

    # Config & integrity
    pdf.add_page()
    page_map["Config & Integrity"] = pdf.page_no()
    _config_page_body(pdf, data, operator, organization)

    return pdf, page_map


# ── Public API ────────────────────────────────────────────────────────────────


def generate_pdf(data: LastPlanData, operator_name: str, organization: str) -> bytes:
    """Generate the full mission report PDF and return as bytes."""
    landing_dist: float | None = None
    if 0 <= data.landing_index < len(data.cum_dists):
        landing_dist = float(data.cum_dists[data.landing_index])

    # Generate all charts once (base64 strings)
    route_img = route_overview_png(
        data.lats,
        data.lons,
        data.agl_arr,
        data.fc.min_agl_m,
        data.poi_indices,
        data.waypoint_indices,
        data.start_index,
        data.landing_index,
        data.fc.point_radius_m,
    )
    agl_img = agl_heatmap_png(data.lats, data.lons, data.agl_arr, data.fc.min_agl_m)
    profile_img = altitude_profile_png(
        data.cum_dists,
        data.final_alts,
        data.terrain_elevs,
        data.fc.min_agl_m,
        data.fc.max_agl_m,
        data.poi_distances,
        landing_dist,
    )
    terrain_img: str | None = None
    if (
        data.terrain_grid is not None
        and data.terrain_grid_lons is not None
        and data.terrain_grid_lats is not None
    ):
        terrain_img = terrain_map_png(
            data.terrain_grid,
            data.terrain_grid_lons,
            data.terrain_grid_lats,
            data.lats,
            data.lons,
            data.poi_indices,
            data.start_index,
            data.landing_index,
        )

    chart_args = (data, operator_name, organization, route_img, agl_img, profile_img, terrain_img)

    # Pass 1: no TOC — capture section page numbers
    _, page_map = _build_pdf(*chart_args, include_toc=False, toc_map=None)

    # Shift all page numbers by +1 (TOC page will be inserted as page 2)
    toc_map = {name: num + 1 for name, num in page_map.items()}

    # Pass 2: include TOC with correct page numbers
    pdf2, _ = _build_pdf(*chart_args, include_toc=True, toc_map=toc_map)

    return bytes(pdf2.output())
